POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
  "longUrl": "https://cloud.mongodb.com/v2/5fbf2756a6c5873a197731ea#metrics/replicaSet/5fbf28e30b8bcf429c48cd5f/explorer/test/urls/find"
}